# Generated by Django 2.1 on 2018-10-16 05:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=110)),
                ('brand', models.CharField(max_length=100)),
                ('choice_field', models.CharField(choices=[('1', 'Poor quality material or workmanship'), ('2', 'Alternate is not equal to brand specified'), ('3', 'Not operating properly - needs frequent repair'), ('4', 'Old or discolored stock'), ('5', 'Other')], default='1', max_length=100)),
                ('complaint_description', models.TextField()),
                ('purchase_date', models.DateField()),
                ('phone_no', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('suggestions', models.TextField()),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=120)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_no', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('product_retailer', models.CharField(max_length=120)),
                ('purchase_date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=39.99, max_digits=6)),
                ('pr', models.IntegerField()),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Smartphone', 'Smartphone'), ('Desktop/Laptop', 'Desktop/Laptop'), ('Refrigerator', 'Refrigerator'), ('Television', 'Television'), ('Others', 'Others')], default='Software', max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('description', models.TextField()),
                ('option_field', models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Both', 'Both')], default='Smartphone', max_length=100)),
                ('address', models.TextField()),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
