# Generated by Django 2.1 on 2018-10-16 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pr',
        ),
    ]
