# Generated by Django 2.1 on 2018-10-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_remove_product_pr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=39.99, max_digits=10),
        ),
    ]
